#!/bin/bash
NowPath="/opt/rasmanger/"
FuncPath=${NowPath}/lib/func.sh

if [ ! -f "$FuncPath" ]; then
    echo "${FuncPath} is not exist"
    exit 1
fi

#include func.sh
. ${FuncPath}

checkFileExist

case ${1} in
    -s)
        showsysInfo ${2}
    ;;

    --update)
        cd 
        rm -rf ${NowPath}
        git clone https://github.com/ZevAlain/rasmanger.git /opt/rasmanger
        cd - >> /dev/null
    ;;

    *)
        showCommandUsager
    ;;

esac


