#!/bin/bash
# NowPath=`/opt/rasmanger`
NowPath=$(cd "$(dirname "$0")"; pwd)  
FuncPath=${NowPath}/lib/func.sh

#include func.sh
. ${FuncPath}

case ${1} in
    -s)
        showcputemp ${2}
    ;;

    *)
        showCommandUsager
    ;;

esac


